name: shell commands

on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
     - name: string
       run: echo "welocome"
     - name: multiple script
       run: |
        node -v
        npm -v   
